name: Minify code and push to minified

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Install dependencies
        working-directory: ./Scripts/minify
        run: npm install
      - name: Minify files
        run: node ./Scripts/minify/minify.js
        env:
          OUTPUT_BRANCH: minified
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "Minify files"
          add: "Output/*"
          #branch: ${{ env.OUTPUT_BRANCH }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.OUTPUT_BRANCH }}
