name: Minify code and push to minified

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install dependencies
        working-directory: ./Scripts/minify
        run: npm install
      - name: Minify files
        run: node ./Scripts/minify/minify.js
      - name: Commit changes
        uses: EndBug/add-and-commit@master
        with:
          message: "Minify files"
          default_author: github_actions
